[package]
name = "daml_lf"
description = "API for working with DAML-LF data"
version = "0.1.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
readme = "README.md"
keywords = ["daml", "api", "damllf"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "0.5"
prost = { version = "0.6", features = [ "no-recursion-limit" ] }
prost-derive = "0.6"
zip = "0.5"
yaml-rust = "0.4"
trim-margin = "0.1"
itertools = "0.9"

[build-dependencies]
prost-build = "0.6"