[package]
name = "ping_pong_demo"
version = "0.1.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
edition = "2018"

[dependencies]
daml_ledger_api = { path = "../../daml_ledger_api", features = ["testing"] }
daml_ledger_macro = { path = "../../daml_ledger_macro" }
daml_ledger_util = { path = "../../daml_ledger_util" }
tokio = { version = "0.2", features = [ "macros" ] }
futures = "0.3"
chrono = "0.4"
time = "0.1"
log = "0.4"
log4rs = "0.8"
