[workspace]
members = [
  "daml",
  "daml_grpc",
  "daml_json",
  "daml_macro",
  "daml_codegen",
  "daml_derive",
  "daml_util",
  "daml_lf",
  "examples/ping_pong_demo",
  "examples/rental_demo"
]
exclude = ["examples/darn"]