[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "OpenSSL",
    "MPL-2.0",
    "BSD-3-Clause"
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { allow = ["Zlib"], name = "adler32", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "warn"
notice = "warn"

[bans]
multiple-versions = "allow"