version: 2

jobs:
  build:
    docker:
      - image: fujiapple/rust-daml:1.49-1_9_0-v1
        auth:
          username: fujiapple
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Start sandbox
          command: cd resources/testing_types_sandbox && make run-ci && sleep 10
      - run:
          name: Test all targets
          command: cargo test --workspace --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
