[package]
name = "daml"
version = "0.1.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A smart contract language for building distributed applications on a safe, privacy-aware runtime"
repository = "https://github.com/fujiapple852/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2018"

[dependencies]
daml_ledger_api = { path = "../daml_ledger_api" }
daml_ledger_derive = { path = "../daml_ledger_derive" }
