Fuji.Vehicle:Car:
  title: My Custom Title
  description: Represents a Car
  items:
    driver: the driver of the car
    make: the make of the car
    owner: the owner of the car
    purchase_time: when the car was purchased
    reg_year: the registration year
Fuji.PingPong:Ping:
  description: The demo Ping template
  items:
    count: the number of times ping has ponged
Fuji.JsonTest:Status:
  title: Status XXX
  description: The status of the foo
  items:
    Enabled: The status is enabled
    Disabled: The status is disabled
Fuji.Shape:Color:
  title: Color XXX
  description: A color
  items:
    Red: The color red
    Green: The color green
    Blue: The color blue
    Custom: A custom color
    Other: An RGBA color
