[package]
name = "daml_ledger_codegen"
version = "0.1.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
edition = "2018"

[dependencies]
daml_ledger_derive = { path = "../daml_ledger_derive" }
daml_ledger_api = { path = "../daml_ledger_api" }