[package]
name = "rental_demo"
version = "0.1.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "Rental demo application"
repository = "https://github.com/fujiapple852/rust-daml-bindings"
license = "Apache-2.0"
keywords = ["daml", "api", "ledger"]
categories = ["development-tools"]
edition = "2018"
build = "build.rs"

[dependencies]
daml = { path = "../../daml" }
daml_ledger_api = { path = "../../daml_ledger_api", features = [ "testing" ] }
tokio = { version = "0.2", features = [ "macros" ] }
log = "0.4"
log4rs = "0.11"

[build-dependencies]
daml_ledger_codegen = { path = "../../daml_ledger_codegen" }